swagger: "2.0"
info:
  version: "0.0.1"
  title: 前后分离接口文档设计
  description: |
    文档描述信息 
    <pre>这是一个demo配置</pre>
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /user/login:
    post:
      tags:
        - 授权相关 
      summary: >
        用户登录接口
      description: 登录成功返回当前用户信息，不成功返回错误信息
      parameters:
        - name: userId
          in: formData
          description: 用户标识
          required: true
          type: string
          
        - name: password
          in: formData
          description: 用户密码
          required: true
          type: string
        - name: x-auth-token
          in: header
          description: 授权token
          required: true
          type: string
          
      responses:
        "200":
          description: 登录成功
          schema:
            type: object
            required:
              - data
            properties:
              meta: 
                $ref: "#/definitions/Meta"
            # a pointer to a definition 
              data: 
                $ref: "#/definitions/UserInfo"
        # responses may fall through to errors
        default:
          description: 登录失败
          schema:
            $ref: "#/definitions/ErrorResponse"

# complex objects have schema definitions
definitions:
  Meta:
    type: object
    required:
      - total
      - pageNo
      - pageSize
    properties:
      total:
        type: integer
        format: int64
        description: 符合条件的总记录数
      pageNo:
        type: integer
        description: 当前页码
      pageSize:
        type: integer
        description: 每页记录数
  ErrorResponse:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        description: 用户友好的错误描述信息
  UserInfo:
    type: object
    required:
      - userId
      - userName
    properties:
      userId:
        type: string
        description: 用户标识
      userName:
        type: string
        description: 用于显示的用户名称
      email:
        type: string
        description: 邮箱地址
      
